const wordPairs = [
  { distorted: 'expen_es', correct: 'expenses' },
  { distorted: 'ne_e_ary', correct: 'necessary' },
  { distorted: 'techni__s', correct: 'techniques' },
  { distorted: 'decaffe__', correct: 'decaffeinated' },
  { distorted: '_mplo_e', correct: 'employee' },
  { distorted: 'su_e_ful', correct: 'successful' },
  { distorted: 'len__', correct: 'length' },
  { distorted: 'thou__', correct: 'thought' },
  { distorted: 'cons_t_ntly', correct: 'consistently' },
  { distorted: 'tau__', correct: 'taught' },
  { distorted: 'rec__ve', correct: 'receive' },
  { distorted: 'd__ease', correct: 'disease' },
  { distorted: 'p_rfume', correct: 'perfume' },
  { distorted: 'ch_mp__ne', correct: 'champagne' },
];
